export const RESPONSES = {
  guidance: {
    tooDark:      "Too dark. Move to a brighter area.",
    tooBright:    "Too bright. Avoid direct sunlight or flash.",
    noClothing:   "No clothing detected. Point the camera directly at the garment.",
    tooFar:       "Too far. Move the camera closer to the clothing.",
    tooClose:     "Too close. Move the camera back.",
    moveLeft:     "Move the camera to the left.",
    moveRight:    "Move the camera to the right.",
    moveUp:       "Move the camera up.",
    moveDown:     "Move the camera down.",
    goodPosition: "Good position! Capturing automatically in 3 seconds.",
    countdown2:   "Two.",
    countdown1:   "One.",
    backendOnly:  "Guidance limited. Tap to capture when you are ready.",
    busyBackground: "Place the garment on a plain, contrasting surface for best results.",
  },
  welcome: "What would you like to do?",
  whatsInFocus: {
    noClothing: "No clothing detected. Point the camera at the garment.",
    tooSmall:   "Object too small. Move the camera closer.",
    tooLarge:   "Object too large. Move the camera back a little.",
    ready:      "Clothing in frame. Ready to capture.",
  },
  scanReady: "Camera ready. Point at your outfit, tap Describe to check framing, then tap Capture.",
  analyzing: "Analyzing your outfit. This will take a few seconds.",
  scanning: "Analyzing your outfit.",
  scanComplete: (desc) => `${desc}. Do you want to save this to your wardrobe?`,
  saved: (name) => `${name} saved to your wardrobe.`,
  discarded: "Item discarded.",
  wardrobeEmpty: "Your wardrobe is empty. Scan your first item to get started.",
  wardrobeCount: (n) => `You have ${n} item${n !== 1 ? "s" : ""} in your wardrobe.`,
  itemDeleted: (name) => `${name} deleted from your wardrobe.`,
  itemUpdated: (name) => `${name} updated.`,
  noItemToDelete: "Your wardrobe is empty. Nothing to delete.",
  outfitPrompt: "What occasion are you dressing for?",
  moodPrompt: (occasion) => `${occasion}. What vibe are you going for?`,
  generating: "Let me put together some looks for you.",
  shoppingStart: "Shopping mode active. Point your camera at clothing for real-time feedback.",
  shoppingPaused: "Scanning paused.",
  shoppingResumed: "Scanning resumed.",
  mirrorReady: "Mirror mode. This gives instant feedback on what you are wearing right now. Nothing is saved. Stand back so I can see your full outfit, then tap capture.",
  mirrorAnalyzing: "Analyzing your outfit. Please hold still.",
  authRequired: "Your session expired. Please sign in again and retry.",
  backendUnavailable: "Could not reach the analysis server. Please check your connection and try again.",
  error: "Something went wrong. Please try again.",
  cameraError: "Could not access camera. Please allow camera permission.",
  goBack: "Going back.",
  notSupported: "Voice input is not supported in this browser. Please use Chrome.",
  shortDescOn: "Switched to short descriptions.",
  longDescOn: "Switched to long descriptions.",
};
