export const RESPONSES = {
  welcome: "What would you like to do?",
  scanReady: "Camera ready. Point at your clothing and tap capture, or say capture.",
  scanning: "Analyzing your clothing.",
  scanComplete: (desc) => `${desc}. Do you want to save this to your wardrobe?`,
  saved: (name) => `${name} saved to your wardrobe.`,
  discarded: "Item discarded.",
  wardrobeEmpty: "Your wardrobe is empty. Scan your first item to get started.",
  wardrobeCount: (n) => `You have ${n} item${n !== 1 ? "s" : ""} in your wardrobe.`,
  itemDeleted: (name) => `${name} deleted from your wardrobe.`,
  noItemToDelete: "Your wardrobe is empty. Nothing to delete.",
  outfitPrompt: "What occasion are you dressing for?",
  moodPrompt: (occasion) => `${occasion}. What vibe are you going for?`,
  generating: "Let me put together some looks for you.",
  shoppingStart: "Shopping mode active. Point your camera at clothing for real-time feedback.",
  shoppingPaused: "Scanning paused.",
  shoppingResumed: "Scanning resumed.",
  mirrorReady: "Stand back and capture your full outfit. I will give you an honest assessment.",
  mirrorAnalyzing: "Analyzing your outfit.",
  noDetection: "No clothing detected. Please point the camera directly at a garment and try again.",
  backendUnavailable: "The detection server is unavailable. Please check your connection and try again.",
  error: "Something went wrong. Please try again.",
  cameraError: "Could not access camera. Please allow camera permission.",
  goBack: "Going back.",
  notSupported: "Voice input is not supported in this browser. Please use Chrome.",
};
